---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6.0.2

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v23.2.0

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.14'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run black
        run: black --check .

      - name: Run isort
        run: isort --check-only --profile black .
