---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6.0.2

      - name: Lint Markdown
        uses: DavidAnson/markdownlint-cli2-action@v23.2.0

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install OS dependencies
        run: sudo apt-get update && sudo apt-get install -y fontforge

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run black
        run: black --check .

      - name: Run isort
        run: isort --check-only --profile black .

      - name: Run mypy
        run: mypy --ignore-missing-imports tools/fontbakery/*.py

      - name: Build fonts
        working-directory: ./scripts
        run: ./build.sh

      - name: Font Bakery universal checks
        uses: f-actions/font-bakery@v3.2.0
        with:
          subcmd: "check-universal"
          args: "--error-code-on FATAL"
          path: "fonts/*.otf"
          version: "1.1.0"

      - name: Font Bakery SBMuFL checks
        uses: f-actions/font-bakery@v3.2.0
        with:
          subcmd: "check-profile"
          args: "tools/fontbakery/sbmufl_profile.py"
          path: "fonts/*.otf"
          version: "1.1.0"
